# Generated by Django 3.1.4 on 2021-06-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='join_date',
        ),
    ]
