# Generated by Django 3.1.4 on 2021-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0003_user_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(),
        ),
    ]
