# Generated by Django 3.1.4 on 2021-06-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0006_auto_20210610_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_time_stamp',
            field=models.DateTimeField(),
        ),
    ]
