# Generated by Django 3.1.4 on 2021-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0007_auto_20210610_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
