# Generated by Django 3.1.4 on 2021-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0008_auto_20210610_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
