# Generated by Django 3.1.4 on 2021-06-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('SINO', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('ParentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.mylist')),
            ],
        ),
    ]
