# Generated by Django 3.1.4 on 2021-06-10 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210609_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='ParentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='child', related_query_name='child', to='myApp.mylist'),
        ),
    ]
